name = "mood-tracker"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "mood"
database_id = "2f3ca975-a2e0-4e54-a614-43a4d981c6ae"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "fba452e26c3841348a5b195951dc645d"

[ai]
binding = "AI"

[vars]
ACCESS_TEAM_DOMAIN = "clydeford.cloudflareaccess.com"
ACCESS_AUD = "a2cabf22b57c29a158f06264da430458f519c589a36166a5a53dc7f685368ec4"

[[routes]]
pattern = "mood.clydeford.net"
custom_domain = true
